# Generated by Django 4.2.10 on 2024-03-10 04:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnatomicalMainGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(db_index=True, max_length=7)),
                ("searchable", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AtcImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("element_count", models.PositiveIntegerField(default=0)),
                ("elements_inserted", models.PositiveIntegerField(default=0)),
                ("drugs_inserted", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ChemicalSubstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(db_index=True, max_length=7)),
                ("searchable", models.BooleanField(default=True)),
                (
                    "atc_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="core.atcimport"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("searchable", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FdaImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("drug_aliases_inserted", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True, max_length=510, null=True)),
                ("doi", models.CharField(blank=True, max_length=255, null=True)),
                ("citation", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TherapeuticMainGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(db_index=True, max_length=7)),
                ("searchable", models.BooleanField(default=True)),
                (
                    "atc_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="core.atcimport"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.anatomicalmaingroup"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TherapeuticPharmacologicalSubgroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(db_index=True, max_length=7)),
                ("searchable", models.BooleanField(default=True)),
                (
                    "atc_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="core.atcimport"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.therapeuticmaingroup"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DrugCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drug_categories",
                        to="core.chemicalsubstance",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="drug_categories", to="core.drug"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrugAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("searchable", models.BooleanField(default=True)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="drug_aliases", to="core.drug"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="drug_aliases", to="core.source"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="drug",
            name="atc_category",
            field=models.ManyToManyField(through="core.DrugCategory", to="core.chemicalsubstance"),
        ),
        migrations.CreateModel(
            name="ChemicalTherapeuticPharmacologicalSubgroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(db_index=True, max_length=7)),
                ("searchable", models.BooleanField(default=True)),
                (
                    "atc_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="core.atcimport"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.therapeuticpharmacologicalsubgroup"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="chemicalsubstance",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.chemicaltherapeuticpharmacologicalsubgroup"
            ),
        ),
        migrations.AddField(
            model_name="anatomicalmaingroup",
            name="atc_import",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="core.atcimport"
            ),
        ),
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_name", models.CharField(blank=True, max_length=255, null=True)),
                ("searchable", models.BooleanField(default=False)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="core_search_search__2f2627_gin"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="drugcategory",
            constraint=models.UniqueConstraint(fields=("drug", "category"), name="unique_drug_category"),
        ),
    ]
