# Generated by Django 4.2.10 on 2024-03-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_chemicalsubstance_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anatomicalmaingroup",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chemicalsubstance",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chemicaltherapeuticpharmacologicalsubgroup",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="therapeuticmaingroup",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="therapeuticpharmacologicalsubgroup",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
