# Generated by Django 4.2.10 on 2024-03-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_anatomicalmaingroup_name_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="anatomicalmaingroup",
            constraint=models.UniqueConstraint(fields=("code", "atc_import"), name="unique_anatomical_main_group"),
        ),
        migrations.AddConstraint(
            model_name="chemicalsubstance",
            constraint=models.UniqueConstraint(fields=("code", "atc_import"), name="unique_chemical_substance"),
        ),
        migrations.AddConstraint(
            model_name="chemicaltherapeuticpharmacologicalsubgroup",
            constraint=models.UniqueConstraint(
                fields=("code", "atc_import"), name="unique_chemical_therapeutic_pharmacological_subgroup"
            ),
        ),
        migrations.AddConstraint(
            model_name="therapeuticmaingroup",
            constraint=models.UniqueConstraint(fields=("code", "atc_import"), name="unique_therapeutic_main_group"),
        ),
        migrations.AddConstraint(
            model_name="therapeuticpharmacologicalsubgroup",
            constraint=models.UniqueConstraint(
                fields=("code", "atc_import"), name="unique_therapeutic_pharmacological_subgroup"
            ),
        ),
    ]
