# Generated by Django 4.2.10 on 2024-05-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_searchindex_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Condition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("orpha_code", models.CharField(max_length=15)),
                ("date_updated", models.DateTimeField()),
                ("status", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="OrphaCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OrphaImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("element_count", models.PositiveIntegerField(default=0)),
                ("elements_inserted", models.PositiveIntegerField(default=0)),
                ("drugs_inserted", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ConditionSynonym",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="synonyms", to="core.condition"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConditionOrphaCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("condition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.condition")),
                (
                    "orpha_category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.orphacategory"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="condition",
            name="orpha_category",
            field=models.ManyToManyField(through="core.ConditionOrphaCategory", to="core.orphacategory"),
        ),
        migrations.AddField(
            model_name="condition",
            name="orpha_import",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.orphaimport"),
        ),
    ]
