# Generated by Django 4.2.10 on 2024-05-19 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_condition_orphacategory_orphaimport_conditionsynonym_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="condition",
            name="orpha_import",
        ),
        migrations.RemoveField(
            model_name="orphaimport",
            name="drugs_inserted",
        ),
        migrations.AlterField(
            model_name="condition",
            name="status",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="OrphaEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("orpha_code", models.CharField(max_length=15)),
                ("description", models.CharField(max_length=2048)),
                ("date_updated", models.DateTimeField()),
                ("status", models.CharField(max_length=255)),
                (
                    "orpha_import",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.orphaimport"),
                ),
            ],
        ),
    ]
