# Generated by Django 4.2.10 on 2024-05-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_condition_orpha_import_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="description",
            field=models.CharField(default="default", max_length=2048),
            preserve_default=False,
        ),
    ]
