# Generated by Django 4.2.10 on 2024-05-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_condition_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="description",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="orphaentry",
            name="description",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
