# Generated by Django 4.2.10 on 2024-05-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_condition_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="searchable",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="condition",
            name="orpha_code",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
