# Generated by Django 4.2.10 on 2024-05-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_enable_pg_trgm"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE INDEX idx_search_vector ON core_searchindex USING gin(search_vector);
            CREATE INDEX idx_similarity_name ON core_searchindex USING gist(name gist_trgm_ops);
            CREATE INDEX idx_searchable ON core_searchindex(searchable);
            CREATE INDEX idx_searchindex_content_type_id_object_id ON core_searchindex (content_type_id, object_id);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_search_vector;
            DROP INDEX IF EXISTS idx_similarity_name;
            DROP INDEX IF EXISTS idx_searchable;
            DROP INDEX IF EXISTS idx_searchindex_content_type_id_object_id;
            """
        ),
    ]
