# Generated by Django 4.2.10 on 2024-05-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20240522_1757"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP INDEX IF EXISTS idx_similarity_name;
            CREATE INDEX idx_similarity_name ON core_searchindex USING gin(name gin_trgm_ops);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_similarity_name;
            CREATE INDEX idx_similarity_name ON core_searchindex USING gist(name gist_trgm_ops);
            """
        ),
    ]
