# Generated by Django 4.2.10 on 2024-05-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_searchindex_name_gin_trgm_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQueryLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.CharField(max_length=255, unique=True)),
                ("count", models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
