blacklist = ['diuretics',
             'potassium-sparing agents',
             'acids',
             'thiazides',
             'Organic nitrates',
             'psycholeptics',
             'combinations with other drugs',
             'Omega-3-triglycerides',
             'other esters',
             'whole root',
             'Invert sugar',
             'psycholeptics',
             'Organic nitrates',
             'psycholeptics',
             'Oil',
             'Zinc protein complex',
             'protease etc.)',
             'antiflatulents',
             'Mineral salts in combination',
             'acid preparations',
             'Lactic acid producing organisms',
             'Liquid paraffin',
             'Multienzymes (lipase',
             'Guar gum',
             'Contact laxatives',
             'Various',
             'Carbon dioxide producing drugs',
             'human',
             'Absorbable gelatin sponge',
             'Gelatin agents',
             'x',
             'minerals',
             'Amino acids',
             'proton pump inhibitors',
             'vii',
             'electrolytes',
             'Stem cells',
             'umbilical cord blood',
             'plasma derived',
             'plasma protein fractions',
             'multivitamins',
             'combinations',
             'x',
             'ii',
             'combination',
             'drugs',
             'Cardioplegia solutions',
             'proton pump inhibitors',
             'potassium salts',
             'supplements',
             'Imidazoles',
             'antibiotics',
             'Zinc bandage',
             'antiseptics',
             'metallic',
             'corticosteroids',
             'omega-3 fatty acids',
             'Aluminium preparations',
             'other esters',
             'Others',
             'other drugs',
             'other potassium salts',
             'Other plasma protein fractions',
             'incl. combinations',
             'Various combinations',
             'triazoles',
             'incl. combinations',
             'other combinations',
             'Vaginal ring',
             'Plastic iud',
             'Conjugated estrogens',
             'imidazole derivatives',
             'Thyroid gland preparations',
             'purified polysaccharides antigen conjugated',
             '33',
             'purified antigen conjugated',
             'Papillomavirus (human types 6',
             'Haemophilus influenzae b',
             'Vaccinia immunoglobulin',
             'rna-based vaccine',
             'Meningococcus a,c',
             'tetravalent purified polysaccharides antigen',
             'Diphtheria-hepatitis b-tetanus',
             'Rabies',
             'Mumps',
             'Diphtheria-haemophilus influenzae b-pertussis-tetanus-hepatitis b',
             'live attenuated',
             'monkeypox vaccines',
             'Gas-gangrene sera',
             'Other meningococcal monovalent purified polysaccharides antigen',
             'Meningococcus b',
             '31',
             'Smallpox',
             'conjugated',
             'purified polysaccharide antigen',
             'oral',
             'Rubella',
             'Hepatitis a',
             '58)',
             'inactivated virus',
             'Malaria vaccines',
             'Meningococcus a,c,y,w-135',
             'typhoid vaccine',
             'Papillomavirus (human types 16',
             '45',
             'Zoster',
             'japanese',
             'whole virus',
             'Cholera',
             'live',
             '18)',
             '16',
             'Leptospira vaccines',
             'Other meningococcal polyvalent purified polysaccharides antigen',
             'Diphtheria-haemophilus influenzae b-pertussis-tetanus-hepatitis b-meningococcus a + c',
             'non-replicating',
             'reassorted',
             'toxoids',
             'multicomponent vaccine',
             'split virus or surface antigen',
             'Covid-19',
             'Rota virus',
             'Measles',
             'poliomyelitis',
             'penicillins',
             'tetravalent purified polysaccharides antigen conjugated',
             'virus-like particles',
             'tick borne immunoglobulin',
             'for extravascular adm.',
             'trivalent',
             'normal human',
             'hepatitis b',
             'Yellow fever',
             'for intravascular adm.',
             'virus like particles',
             'whole cell',
             'Poliomyelitis oral',
             'bivalent purified polysaccharides antigen',
             'protein subunit',
             'Diphtheria-haemophilus influenzae b-pertussis-poliomyelitis-tetanus',
             'Diphtheria-pertussis-poliomyelitis-tetanus',
             'Diphtheria-haemophilus influenzae b-pertussis-poliomyelitis-tetanus-hepatitis b',
             'Pneumococcus purified polysaccharides antigen',
             'outer membrane vesicle vaccine',
             'Respiratory syncytial virus vaccines',
             'haemophilus influenzae',
             'purified polysaccharides antigen',
             '52',
             'monovalent',
             '18',
             'Typhoid-hepatitis a',
             'Enterovirus 71 vaccines',
             '11',
             'inactivated',
             'beta-lactamase inhibitor',
             'mumps',
             'other antibacterials'
             'Magnesium (different salts',
             'Escherichia coli',
             'Mineral salts',
             'Calcium (different salts',
             'Phospholipids',
             'Cascara',
             'Ordinary salt combinations',
             'other minerals',
             'trace elements',
             'Potassium (different salts',
            ]

delimiters = [' and ',
              ', ',
              '/',
              ' in ',
              ' with ',
              ' incl. ',
              ' excl. ',
              ' other ',
              ' of ',
              ' without ',
              ' various ',
              ' from ',
              ' preparations ',
              ]