#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset



# N.B. If only .env files supported variable expansion...
export CELERY_BROKER_URL="${REDIS_URL}"


if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

python << END
import sys
import time

import psycopg

suggest_unrecoverable_after = 5 # default 30
start = time.time()

connection_params = {
    "dbname": "${POSTGRES_DB}",
    "user": "${POSTGRES_USER}",
    "password": "${POSTGRES_PASSWORD}",
    "host": "${POSTGRES_HOST}",
    "port": "${POSTGRES_PORT}",
}

use_ssl = ${POSTGRES_USE_SSL} in [True, 'True']

if use_ssl:
    print("We're using SSL")
    ssl_params = {
        "sslmode": "require",
        "sslrootcert": "${DB_SSLROOTCERT}",
        "sslcert": "${DB_SSLCERT}",
        "sslkey": "${DB_SSLKEY}",
    }

    connection_params.update(ssl_params)

    print(connection_params)

while True:
    try:
        psycopg.connect(**connection_params)
        break
    except psycopg.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            #sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))
            break
    time.sleep(1)
END

>&2 echo 'PostgreSQL is available'

exec "$@"
